services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: r_auth_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    command: start-dev